# Generated by Django 4.1.2 on 2022-10-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_empleado_options_empleado_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='image',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
